# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdatapro
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true